# vmp-http-spec - OpenAPI Specification for the vmp-server HTTP interface
# Copyright (C) 2023 Hugo Melder
# 
# SPDX-License-Identifier: MIT

type: object
title: PipelineItem
description: A single Pipeline.
required:
  - type
  - friendlyName
  - description
  - pipelineId
  - element_id
  - state
properties:
  type:
    type: string
    description: Type of the pipeline.
    enum:
      - ingress
      - egress
  friendlyName:
    type: string
    description: Friendly name of the pipeline.
  description:
    type: string
    description: Description of the pipeline.
  pipelineId:
    type: integer
    description: ID of the pipeline.
  element_id:
    type: string
    description: Gstreamer bin of the pipeline.
  state:
    type: string
    description: Gstreamer State of the pipeline.
    enum:
      - STATE_NULL
      - STATE_READY
      - STATE_PAUSED
      - STATE_PLAYING