# vmp-http-spec - OpenAPI Specification for the vmp-server HTTP interface
# Copyright (C) 2023 Hugo Melder
# 
# SPDX-License-Identifier: MIT

openapi: 3.0.0
info:
  title: vmp-http-spec
  description: OpenAPI Specification for the vmp-server HTTP interface
  version: 0.0.1
paths:
  $ref: './paths/_index.yml'
components:
  parameters:
  $ref: './components/parameters/_index.yml'
  schemas:
    $ref: './components/schemas/_index.yml'
  examples:
    $ref: './components/examples/_index.yml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []