name: CI
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup nix environment
      run: nix-shell
    - name: CalendarKit Tests
      run: |
        nix-shell --run "
        cd Libraries/CalendarKit &&
        meson setup build &&
        ninja -C build test
        "
    - name: MicroHTTPKit Tests
      run: |
        nix-shell --run "
        cd Libraries/MicroHTTPKit &&
        meson setup build &&
        ninja -C build test
        "